spring:
  application:
    name: SesacSemi2
  datasource:
    url: jdbc:mysql://localhost:3306/sesac
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2s

jwt :
  secret-key: ${JWT_SECRET_KEY}
  access-expire-time: ${JWT_ACCESS_EXPIRE_TIME}
  refresh-expire-time: ${JWT_REFRESH_EXPIRE_TIME}
