name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. GitHub Repository Clone
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Build the JAR file with Gradle
      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      # 4. Docker Compose 설치
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # 설치 확인

      # 5. Docker 이미지 빌드
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag hyungs0703/sesacsemi2:latest

      # 6. Docker Compose로 서비스 실행 및 테스트
      - name: Start Docker Compose services and run tests
        run: |
          docker-compose -f docker-compose.yml up -d  # 서비스 백그라운드 실행
          docker-compose exec springboot-app ./gradlew test  # 테스트 실행
          docker-compose down  # 실행된 서비스 종료

      # 7. Docker Hub 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 8. Docker 이미지 푸시
      - name: Push the Docker image
        run: docker push hyungs0703/sesacsemi2:latest
