name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Gradle 빌드 실행 (JAR 파일 생성)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3.권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      # 4. Docker 이미지 빌드 (ARM64 아키텍처용)
      - name: Build the Docker image
        run: |
          docker build --platform linux/arm64 -t hyungs0703/sesacsemi2:latest .

      # 4. Docker Hub 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5. Docker 이미지 푸시
      - name: Push the Docker image
        run: |
          docker push hyungs0703/sesacsemi2:latest
