name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. GitHub Repository Clone
    - uses: actions/checkout@v4

    # 2. Docker 이미지 빌드
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag hyungs0703/SesacSemi2:latest --tag hyungs0703/SesacSemi2:${{ github.sha }}

    # 3. Docker Hub 로그인
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 4. Docker 이미지 푸시
    - name: Push the Docker image
      run: |
        docker push hyungs0703/SesacSemi2:latest
        docker push hyungs0703/SesacSemi2:${{ github.sha }}
