name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. GitHub Repository Clone
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Gradle 빌드 실행 (JAR 파일 생성)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      # 3. Docker 이미지 빌드
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag hyungs0703/sesacsemi2:latest

      # 4. Docker 서비스 실행 (백그라운드 실행)
      - name: Run docker-compose up -d
        run: |
          docker-compose -f docker-compose.yml up -d

      # 5. Docker 컨테이너에서 테스트 실행
      - name: Run tests inside Docker container
        run: |
          docker-compose exec springboot-app ./gradlew test

      # 6. Docker 서비스 종료
      - name: Docker-compose down
        run: docker-compose down

      # 7. Docker Hub 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 8. Docker 이미지 푸시
      - name: Push the Docker image
        run: docker push hyungs0703/sesacsemi2:latest
